### ISSUE TITLE
Explain how scripts run

### ISSUE THREAD

**Issue by stsievert** [ItaySafran/OneLayerGDconvergence#1]
Either via putting a couple lines in the README.md or via using shell scripts. I'd like to see 

* how minima are generated (which are saved in `Results`?)
* how results are read in and verified

I can't see how the functions defined in this repo are called. I see there are some files in the git history that would help with this (runExp.csh, run_findBadMinima.csh). It'd be helpful to have these back, but it wouldn't resolve the second issue about reading in results and verifying.

I'm reading the paper behind this repo ("Spurious local minima are common ...") at UW–Madison for a 900-level machine learning class. I'll be presenting on Friday, and was looking at this repo to see exactly where symbolic calculations are used.

**Comment by ItaySafran** [comment]
I apologize for the late response. My email notification seems like it is set correctly but I did not receive any email regarding this.

The parts where symbolic calculations were used are described by comments inside the code in the .m files. How was the presentation?

**Comment by stsievert** [comment]
> were used are described by comments inside the code in the .m files.

I'm only seeing function documentation that describe the inputs and outputs, at least for the functions I've seen. I'd like to see

- scripts that call the functions (all functions I've seen have inputs – where does that input come from?)
- tests to make sure the functions work as expected

**Comment by ItaySafran** [comment]
If you look at the 'minimum' function for instance, you can see that it uses symbolic computation wherever the 'sym' Matlab function is used, e.g. lines 26, 28, 30, etc...
It also calls other functions that use symbolic computation such as 'maxthirdderivative', 'froNorm'...

The minimum function is the function that uses the most symbolic computations if I'm not mistaken, and is responsible for verifying the conditions in the key lemma, as well as deriving the radius upper bound for the ball enclosing a local minimum.

As for tests, most functions were tested internally in Matlab using simple examples, but I also wrote a test for verifying the Hessian of the objective as computed in the paper. What I did was to compute the Hessian both using the formula derived as well as estimate it numerically using slopes of randomly generated points, and then compare the two results. This helps verify that the computation of the Hessian is correct.
